clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
            name: Bootstrap
            image: deeson/deployer
            script:
              - make pipelines-bootstrap
            artifacts:
              - 'scripts/make/**'
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.1-2.4.3
          caches:
            - composer
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: deeson/fe-node
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'src/frontend/assets/**'
            - 'src/frontend/node_modules/**'
      - step:
          name: Test Build
          image: wodby/drupal-php:7.1-2.4.3
          script:
            - make pipelines-test-standards
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy
    develop:
      - step:
          name: Bootstrap
          image: deeson/deployer
          script:
            - make pipelines-bootstrap
          artifacts:
            - 'scripts/make/**'
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.1-2.4.3
          caches:
            - composer
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: deeson/fe-node
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'src/frontend/assets/**'
            - 'src/frontend/node_modules/**'
      - step:
          name: Test Build
          image: wodby/drupal-php:7.1-2.4.3
          script:
            - make pipelines-test-standards
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy
    UAT:
      - step:
          name: Bootstrap
          image: deeson/deployer
          script:
            - make pipelines-bootstrap
          artifacts:
            - 'scripts/make/**'
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.1-2.4.3
          caches:
            - composer
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: deeson/fe-node
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'src/frontend/assets/**'
            - 'src/frontend/node_modules/**'
      - step:
          name: Test Build
          image: wodby/drupal-php:7.1-2.4.3
          script:
            - make pipelines-test-standards
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy
  tags:
    '*':
      - step:
          name: Bootstrap
          image: deeson/deployer
          script:
            - make pipelines-bootstrap
          artifacts:
            - 'scripts/make/**'
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.1-2.4.3
          caches:
            - composer
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: deeson/fe-node
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'src/frontend/assets/**'
            - 'src/frontend/node_modules/**'
      - step:
          name: Test Build
          image: wodby/drupal-php:7.1-2.4.3
          script:
            - make pipelines-test-standards
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy

definitions:
  caches:
    drush: ~/.drush/cache
    node: src/frontend/node_modules
