version: "3"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    ports:
#      - "3307:3306"
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # A starter database is inside here
      - ./.persist/mysql:/var/lib/mysql:delegated # I want to manage volumes manually.
    networks:
      - default

  php:
    image: wodby/drupal-php:7.3-dev
    container_name: "${PROJECT_NAME}_php"
    environment:
      DOCKER_LOCAL: 1
      D4D_HOSTNAME: ${PROJECT_BASE_URL}
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80
      PHP_IDE_CONFIG: "serverName=drupal"       # Needed for xdebug for drush commands.
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      #PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
      #PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03, You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
      #PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
      #PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
    volumes:
      - ./:/var/www/html:cached
      - ./.persist/public:/var/www/html/docroot/sites/default/files:delegated
      - ./.persist/private:/private:delegated
    tmpfs: /tmp
    networks:
      - default

  nginx:
    image: wodby/nginx:1.17-5.5.0
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
      NGINX_VHOST_PRESET: drupal8
    volumes:
      - ./:/var/www/html:cached
      - ./.persist/public:/var/www/html/docroot/sites/default/files:delegated
    tmpfs: /tmp
    networks:
      - default
      - proxy
    labels:
      - 'traefik.docker.network=proxy'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  solr:
    image: wodby/drupal-solr:8-6.4-2.0.0
    container_name: "${PROJECT_NAME}_solr"
    environment:
      SOLR_HEAP: 1024m
    volumes:
      - ./.persist/solr:/opt/solr/server/solr/core1:delegated
    networks:
      - default
      - proxy
    labels:
      - 'traefik.docker.network=proxy'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    networks:
      - default
      - proxy
    labels:
      - 'traefik.docker.network=proxy'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

#  memcached:
#    image: wodby/memcached:1-2.2.6
#    container_name: "${PROJECT_NAME}_memcached"
#    networks:
#      - default

  redis:
    image: wodby/redis:4-3.0.8
    container_name: "${PROJECT_NAME}_redis"
    networks:
      - default

  fe-node:
    image: deeson/fe-node
    container_name: "${PROJECT_NAME}_fe-node"
    depends_on:
      - 'fe-php'
    volumes:
      - ./src/frontend:/app:delegated
    working_dir: /app
    environment:
      DOCKER_LOCAL: 1
    command: bash -c 'yarn install && yarn start'
    networks:
      - default
      - proxy
    labels:
      - 'traefik.docker.network=proxy'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:frontend.${PROJECT_BASE_URL}'

  fe-php:
    image: deeson/fe-php
    container_name: "${PROJECT_NAME}_fe-php"
    volumes:
      - ./src/frontend:/app:delegated
    working_dir: /app
    environment:
      DOCKER_LOCAL: 1
    command: bash -c 'composer install && node_modules/.bin/deeson-router-start.sh'
    networks:
      - default

#  varnish:
#    image: wodby/drupal-varnish:4.1-2.1.0
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.${PROJECT_BASE_URL}'

networks:
  proxy:
    external: true
